export type Datastore = {
        "id": number | string,
        "Versand":number | string,
        "Tagesprio":number | string,
        "Versandart": number | string,
        "Einbaudatum": number | string,
        "Kunde": number | string,
        "Tankform": number | string,
        "Kunststoff": number | string,
        "Volumen": number | string,
        "Vlies": number | string,
        "Notizen": number | string,
        "Huellennr.": number | string,
        "MA": number | string,
        "Zuschnitt": number | string,
        "gefahren": number | string,
        "zumachen": number | string,
        "pruefen": number | string,
        "Sonderaufgaben": number | string,
        "verpackt": number | string,
        "vernaeht-verpackt": number | string,
        "Paket": number | string,
        "Packmasse": number | string,
        "Dachser": number | string,
        "Kommission": number | string,
        "orderdate": number | string,
}